services:
  springboot-app:
    build:
      context: ./springboot-chal
    container_name: sechamp2025_app
    ports:
      - "8080:8080"
    networks:
      - my_network
    depends_on:
      mysql-db:
        condition: service_healthy
    restart: unless-stopped
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/secchamp2025?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=P@ssw0rd 


  tomcat-chal:
    image: tomcat:9.0
    container_name: tomcat-chal
    ports:
      - "18080:8080"
    volumes:
      - ./tomcat-chal:/usr/local/tomcat/webapps/proxy/18080
    networks:
      - my_network

  mysql-db:
    build: ./db
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: P@ssw0rd
    ports:
      - "3306:3306"
    networks:
      - my_network
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -pP@ssw0rd && mysql -u root -pP@ssw0rd -e 'SELECT 1' secchamp2025 || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 30s

networks:
  my_network:
    driver: bridge

volumes:
  mysql-data: